### ISSUE TITLE
Implement a new database engine

### ISSUE THREAD

**Issue by misha1301** [TNTU-RS-internship/superset#2]
### Superset Improvement Proposal (SIP)-1: Adding Custom Icons to the Database Connection Form (For MySQL Database)

**Abstract**
The goal is to enhance the user interface of the database connection form by adding custom icons for MySQL databases.

**Motivation**
The current database connection form lacks visual cues that can improve user experience. By duplicating icons from the given URL and the [+Database] in STEP 1, we can make the form more intuitive and user-friendly.

**Backend**
Implement the following steps:
- [x] Implement a new database engine and make the database available at the /available/ endpoint. This involves creating a new class in the db_engine_specs module that defines the behavior of the new engine.

**Configuration**
Implement the following steps:
- [x] Adjust the superset_text.yml file accordingly for each custom type of MySQL database. This file contains the display text for various parts of the Superset application.

### SIP-2: Replicating the Superset Frontend Logic to Generate Dynamic Forms

**Abstract**
The aim is to replicate the Superset frontend logic to generate dynamic forms to connect to external API resources (On Cloud with username/password).

**Motivation**
This change will allow Superset to connect to a wider range of data sources, increasing its versatility and usefulness.

**Backend**
Implement the following steps:
- [ ] Make an API request to a new custom endpoint on the backend with the username/password that will run a custom python script to pull the data into Superset. This involves creating a new API endpoint and a Python script that fetches data from the external API.

**Comment by sorokivski** [comment]
connection established with localhost, now with cloud services. solution for remote connection reqires few more methods like: do_post method and generating json for transferring data to cloud services, like was implemented in this [commit](https://github.com/rework-space-com/superset/commit/b84015e0ebcba90bd9d956c3f77af74cf58443ea#diff-27da6058e90560d6d332607c0686ab8dbdf580c3ceb05e135c7c97bd2b4dc24d)
